// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBD_GIBDD.Data;

namespace WebBD_GIBDD.Migrations
{
    [DbContext(typeof(WebBD_GIBDDContext))]
    [Migration("20201101101548_Init01.11")]
    partial class Init0111
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BD_GIBDD.Models.Auto", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BrandAutoID")
                        .HasColumnType("bigint");

                    b.Property<string>("COLOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfRegistration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTechInspection")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DriverID")
                        .HasColumnType("bigint");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumTechPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberCarBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<string>("TechInspection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BrandAutoID");

                    b.HasIndex("DriverID");

                    b.HasIndex("StaffID");

                    b.ToTable("Auto");
                });

            modelBuilder.Entity("BD_GIBDD.Models.BrandAuto", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndProduction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartProduction")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BrandAuto");
                });

            modelBuilder.Entity("BD_GIBDD.Models.CarsStolen", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AutoID")
                        .HasColumnType("bigint");

                    b.Property<string>("Circumstances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAppeal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFind")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStolen")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DriverID")
                        .HasColumnType("bigint");

                    b.Property<bool>("MarkFind")
                        .HasColumnType("bit");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("AutoID");

                    b.HasIndex("DriverID");

                    b.HasIndex("StaffID");

                    b.ToTable("CarsStolen");
                });

            modelBuilder.Entity("BD_GIBDD.Models.Driver", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateIssueCertificate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DriversLicenseNum")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndDateCertificate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StaffID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("BD_GIBDD.Models.Position", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Duties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("BD_GIBDD.Models.Rank", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Duties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("BD_GIBDD.Models.Staff", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<long?>("PositionID")
                        .HasColumnType("bigint");

                    b.Property<long?>("RankID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PositionID");

                    b.HasIndex("RankID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("BD_GIBDD.Models.Auto", b =>
                {
                    b.HasOne("BD_GIBDD.Models.BrandAuto", "BrandAuto")
                        .WithMany("Auto")
                        .HasForeignKey("BrandAutoID");

                    b.HasOne("BD_GIBDD.Models.Driver", "Driver")
                        .WithMany("Auto")
                        .HasForeignKey("DriverID");

                    b.HasOne("BD_GIBDD.Models.Staff", "Staff")
                        .WithMany("Auto")
                        .HasForeignKey("StaffID");
                });

            modelBuilder.Entity("BD_GIBDD.Models.CarsStolen", b =>
                {
                    b.HasOne("BD_GIBDD.Models.Auto", "Auto")
                        .WithMany()
                        .HasForeignKey("AutoID");

                    b.HasOne("BD_GIBDD.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.HasOne("BD_GIBDD.Models.Staff", "Staff")
                        .WithMany("CarsStolen")
                        .HasForeignKey("StaffID");
                });

            modelBuilder.Entity("BD_GIBDD.Models.Driver", b =>
                {
                    b.HasOne("BD_GIBDD.Models.Staff", "Staff")
                        .WithMany("Driver")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BD_GIBDD.Models.Staff", b =>
                {
                    b.HasOne("BD_GIBDD.Models.Position", "Position")
                        .WithMany("Staff")
                        .HasForeignKey("PositionID");

                    b.HasOne("BD_GIBDD.Models.Rank", "Rank")
                        .WithMany("Staff")
                        .HasForeignKey("RankID");
                });
#pragma warning restore 612, 618
        }
    }
}
